### ISSUE TITLE
ceph-csi overrides ceph.conf managed by other charms and breaks services e.g. Ceph OSD

### ISSUE THREAD

**Issue by nobuto-m** [charmed-kubernetes/ceph-csi-operator#22]
Let's assume hyper-converged deployment of K8s and Ceph. 3 nodes will have microk8s units respectively for hosting containers and at the same time Ceph OSD services are running in the same set of nodes to offer persistent storage for k8s.

By having the architecture, restarting a node or OSD services leads to OSD startup failure.

The easiest way I can think of to fix it is to use `/var/lib/charm/<APP_NAME>/ceph.conf` by following the Charmed Ceph and Charmed OpenStack ecosystem and NOT to assume the sole ownership of `/etc/ceph/ceph.conf` in a node.

https://github.com/charmed-kubernetes/ceph-csi-operator/blob/70b81d9ba5b204edd3a70028adb5b908b401b586/src/charm.py#L230-L231

### juju status

Juju status will look like the following (3 nodes with microk8s + ceph-osd).
```
$ juju status
Model  Controller       Cloud/Region  Version  SLA          Timestamp
ceph   maas-controller  maas/default  3.5.3    unsupported  06:41:26Z

App       Version          Status  Scale  Charm     Channel        Rev  Exposed  Message
ceph-csi  v3.9.0,v0,v3...  active      3  ceph-csi  1.28/stable     37  no       Versions: cephfs=v3.9.0, config=v0, rbd=v3.9.0
ceph-mon  17.2.7           active      3  ceph-mon  quincy/stable  215  no       Unit is ready and clustered
ceph-osd  17.2.7           active      3  ceph-osd  quincy/stable  621  no       Unit is ready (1 OSD)
microk8s  1.28.13          active      3  microk8s  1.28/stable    213  no       node is ready

Unit           Workload  Agent  Machine  Public address   Ports      Message
ceph-mon/0     active    idle   0/lxd/0  192.168.151.105             Unit is ready and clustered
ceph-mon/1*    active    idle   1/lxd/0  192.168.151.107             Unit is ready and clustered
ceph-mon/2     active    idle   2/lxd/0  192.168.151.106             Unit is ready and clustered
ceph-osd/0     active    idle   0        192.168.151.102             Unit is ready (1 OSD)
ceph-osd/1*    active    idle   1        192.168.151.104             Unit is ready (1 OSD)
ceph-osd/2     active    idle   2        192.168.151.103             Unit is ready (1 OSD)
microk8s/0*    active    idle   0        192.168.151.102  16443/tcp  node is ready
  ceph-csi/2   active    idle            192.168.151.102             Unit is ready
microk8s/1     active    idle   1        192.168.151.104  16443/tcp  node is ready
  ceph-csi/0*  active    idle            192.168.151.104             Unit is ready
microk8s/2     active    idle   2        192.168.151.103  16443/tcp  node is ready
  ceph-csi/1   active    idle            192.168.151.103             Unit is ready

Machine  State    Address          Inst id              Base          AZ       Message
0        started  192.168.151.102  machine-2            ubuntu@22.04  default  Deployed
0/lxd/0  started  192.168.151.105  juju-1bd4bb-0-lxd-0  ubuntu@22.04  default  Container started
1        started  192.168.151.104  machine-3            ubuntu@22.04  default  Deployed
1/lxd/0  started  192.168.151.107  juju-1bd4bb-1-lxd-0  ubuntu@22.04  default  Container started
2        started  192.168.151.103  machine-4            ubuntu@22.04  default  Deployed
2/lxd/0  started  192.168.151.106  juju-1bd4bb-2-lxd-0  ubuntu@22.04  default  Container started
```

This is a working setup just after the deployment.

### OSD start up failure

However, ceph.conf written by ceph-osd charm was already overwritten by ceph-csi in an incompatible way. So restarting OSDs (including a host reboot) fails to bring up the service.

```
$ sudo systemctl status ceph-osd@1.service 
× ceph-osd@1.service - Ceph object storage daemon osd.1
     Loaded: loaded (/lib/systemd/system/ceph-osd@.service; enabled-runtime; vendor preset: enabled)
     Active: failed (Result: exit-code) since Sat 2024-08-31 06:52:33 UTC; 33s ago
    Process: 200078 ExecStartPre=/usr/lib/ceph/ceph-osd-prestart.sh --cluster ${CLUSTER} --id 1 (code=exited, status=0/SUCCESS)
    Process: 200082 ExecStart=/usr/bin/ceph-osd -f --cluster ${CLUSTER} --id 1 --setuser ceph --setgroup ceph (code=exited, status=1/FAILURE)
   Main PID: 200082 (code=exited, status=1/FAILURE)
        CPU: 166ms
```

```
Aug 31 06:52:31 machine-2 systemd[1]: Starting Ceph object storage daemon osd.1...
Aug 31 06:52:31 machine-2 systemd[1]: Started Ceph object storage daemon osd.1.
Aug 31 06:52:31 machine-2 ceph-osd[200082]: 2024-08-31T06:52:31.904+0000 7f8d36bee800 -1 auth: unable to find a keyring on /etc/ceph/ceph.osd.1.keyring: (2) No such file or directory
Aug 31 06:52:31 machine-2 ceph-osd[200082]: 2024-08-31T06:52:31.904+0000 7f8d36bee800 -1 AuthRegistry(0x558d150f0138) no keyring found at /etc/ceph/ceph.osd.1.keyring, disabling cephx
Aug 31 06:52:31 machine-2 ceph-osd[200082]: 2024-08-31T06:52:31.904+0000 7f8d36bee800 -1 auth: unable to find a keyring on /etc/ceph/ceph.osd.1.keyring: (2) No such file or directory
Aug 31 06:52:31 machine-2 ceph-osd[200082]: 2024-08-31T06:52:31.904+0000 7f8d36bee800 -1 AuthRegistry(0x7ffd1bf41d90) no keyring found at /etc/ceph/ceph.osd.1.keyring, disabling cephx
Aug 31 06:52:31 machine-2 ceph-osd[200082]: failed to fetch mon config (--no-mon-config to skip)
Aug 31 06:52:31 machine-2 systemd[1]: ceph-osd@1.service: Main process exited, code=exited, status=1/FAILURE
Aug 31 06:52:31 machine-2 systemd[1]: ceph-osd@1.service: Failed with result 'exit-code'.
```

### ceph.conf conflict

`/etc/ceph/ceph.conf` is a symlink to `/etc/alternatives/ceph.conf`, and it's a symlink to `/var/lib/charm/ceph-osd/ceph.conf` in ceph-osd charm's case.

```bash
# ls -alF /etc/ceph/
total 12
drwxr-xr-x   2 root root 4096 Aug 31 04:45 ./
drwxr-xr-x 102 root root 4096 Aug 31 04:40 ../
lrwxrwxrwx   1 root root   27 Aug 31 04:45 ceph.conf -> /etc/alternatives/ceph.conf
-rw-r--r--   1 root root   92 Feb  8  2024 rbdmap

# ls -alF /etc/alternatives/ceph.conf
lrwxrwxrwx 1 root root 33 Aug 31 04:45 /etc/alternatives/ceph.conf -> /var/lib/charm/ceph-osd/ceph.conf

# update-alternatives --display ceph.conf
ceph.conf - auto mode
  link best version is /var/lib/charm/ceph-osd/ceph.conf
  link currently points to /var/lib/charm/ceph-osd/ceph.conf
  link ceph.conf is /etc/ceph/ceph.conf
/var/lib/charm/ceph-osd/ceph.conf - priority 90
```

#### /var/lib/charm/ceph-osd/ceph.conf with ceph-osd

```
[global]
auth cluster required = cephx
auth service required = cephx
auth client required = cephx

mon host = 192.168.151.105 192.168.151.106 192.168.151.107
fsid = d5884b78-6753-11ef-9ec6-9d97ba9e7ea0

log to syslog = false
err to syslog = false
clog to syslog = false
debug osd = 1/5

public network = 
cluster network = 
public addr = 192.168.151.102
cluster addr = 192.168.151.102

[client.osd-upgrade]
keyring = /var/lib/ceph/osd/ceph.client.osd-upgrade.keyring

[client.osd-removal]
keyring = /var/lib/ceph/osd/ceph.client.osd-removal.keyring

[client.crash]
keyring = /var/lib/ceph/osd/ceph.client.crash.keyring

[mon]
keyring = /var/lib/ceph/mon/$cluster-$id/keyring

[mds]
keyring = /var/lib/ceph/mds/$cluster-$id/keyring

[osd]
keyring = /var/lib/ceph/osd/$cluster-$id/keyring

osd objectstore = bluestore

bluestore compression algorithm = lz4
bdev enable discard = True
bdev async discard = True
```

#### /var/lib/charm/ceph-osd/ceph.conf overridden by ceph-csi charm

It's missing the necessary pieces to start up Ceph OSD services.

```
[global]
auth cluster required = cephx
auth service required = cephx
auth client required = cephx
keyring = /etc/ceph/$cluster.$name.keyring
mon host = 192.168.151.105 192.168.151.106 192.168.151.107
log to syslog = true
err to syslog = true
clog to syslog = true
mon cluster log to syslog = true
debug mon = 1/5
debug osd = 1/5

[client]
log file = /var/log/ceph.log
```

The credit of troubleshooting and diagnosis goes to @odufourc and @shundezhang.

**Comment by nobuto-m** [comment]
I've confirmed it by
`$ juju deploy ./bundle.yaml`
then
`$ juju deploy ./bundle.yaml --overlay ./microk8s.yaml`
to compare ceph.conf before and after.

### bundle.yaml
```yaml
series: jammy
applications:
  ceph-mon:
    charm: ceph-mon
    channel: quincy/stable
    num_units: 3
    to:
    - lxd:0
    - lxd:1
    - lxd:2
    options:
      # LP: #1929262
      config-flags: '{"mon":{"auth allow insecure global id reclaim":"false"}}'
      expected-osd-count: 3
      monitor-count: 3
      source: distro
  ceph-osd:
    charm: ceph-osd
    channel: quincy/stable
    num_units: 3
    to:
    - "0"
    - "1"
    - "2"
    options:
      aa-profile-mode: enforce
      osd-devices: /dev/sdb /dev/vdb
      source: distro
machines:
  "0": {}
  "1": {}
  "2": {}
relations:
- - ceph-osd:mon
  - ceph-mon:osd
```

### microk8s.yaml
```yaml
applications:
  microk8s:
    channel: 1.28/stable
    charm: microk8s
    num_units: 3
    to:
    - 0
    - 1
    - 2
  ceph-csi:
    charm: ceph-csi
    channel: 1.28/stable
    options:
      namespace: kube-system
relations:
- - ceph-csi:ceph-client
  - ceph-mon:client
- - ceph-csi:kubernetes-info
  - microk8s:kubernetes-info
```
